// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpcvoealus8czIDx6YxBH8-_5PKuf9ss8',
    appId: '1:1035521440912:web:bb4cf8edff43eb1b5cac15',
    messagingSenderId: '1035521440912',
    projectId: 'band-crud',
    authDomain: 'band-crud.firebaseapp.com',
    storageBucket: 'band-crud.appspot.com',
    measurementId: 'G-KB20CGE01K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYLHrCBP8ONzV2sYjf4wSejvL4wowhVcI',
    appId: '1:1035521440912:android:ec9137f38d71f8825cac15',
    messagingSenderId: '1035521440912',
    projectId: 'band-crud',
    storageBucket: 'band-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwGKMbSKkLkNUd6XieNh3vbqiMLndXJ0Q',
    appId: '1:1035521440912:ios:8a8ae7d99ac561b35cac15',
    messagingSenderId: '1035521440912',
    projectId: 'band-crud',
    storageBucket: 'band-crud.appspot.com',
    iosClientId: '1035521440912-6u9fc073ir2arppv3dptgfrbs7o073jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoband',
  );
}
